// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxtmywarilkvidocnlsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4dG15d2FyaWxrdmlkb2NubHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDQ2MTIsImV4cCI6MjA3MTg4MDYxMn0.oPoHAyZSVsKnzVglbfDi9o2dhf_XKt-JsJLEaKnj-OU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});